version: '2'
services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/usr/local/src/wellrested

  docs:
    build:
      context: .
      dockerfile: ./docker/docs/Dockerfile
    volumes:
      - .:/usr/local/src/wellrested